<?php



if ( function_exists( 'acf_add_local_field_group' ) ) {
		// General theme settings (parent)
		acf_add_local_field_group(
			array(
				'key'                   => 'theme_setting_fields',
				'title'                 => 'Options',
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'seamless',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
				'location'              => array(
					array(
						array(
							'param'    => 'options_page',
							'operator' => '==',
							'value'    => 'acf-options-theme-settings',
						),
					),
				),
				'fields'                => array(
					array(
						'key'          => 'site_layout',
						'label'        => 'Site layout',
						'name'         => 'site-layout',
						'type'         => 'number',
						'instructions' => 'Change the site layout (px)',
						'placeholder'  => '1600',
						'min'          => '1200',
						'max'          => '2560',
						'append'       => 'px',
					),
					array(
						'key'           => 'block_spacing_v_desktop',
						'label'         => 'Vertical block spacing (desktop)',
						'name'          => 'block-spacing-v-desktop',
						'type'          => 'number',
						'instructions'  => 'Change the vertical spacing for every block on desktop (px)',
						'placeholder'   => '32',
						'default_value' => '32',
						'append'        => 'px',
						'wrapper'       => array(
							'width' => '33',
						),
					),
					array(
						'key'           => 'block_spacing_v_tablet',
						'label'         => 'Vertical block spacing (tablet)',
						'name'          => 'block-spacing-v-tablet',
						'type'          => 'number',
						'instructions'  => 'Change the vertical spacing for every block on tablet (px)',
						'placeholder'   => '32',
						'default_value' => '32',
						'append'        => 'px',
						'wrapper'       => array(
							'width' => '33',
						),
					),
					array(
						'key'           => 'block_spacing_v_mobile',
						'label'         => 'Vertical block spacing (mobile)',
						'name'          => 'block-spacing-v-mobile',
						'type'          => 'number',
						'instructions'  => 'Change the vertical spacing of every block on mobile (px)',
						'placeholder'   => '32',
						'default_value' => '32',
						'append'        => 'px',
						'wrapper'       => array(
							'width' => '33',
						),
					),
					array(
						'key'           => 'block_spacing_h_desktop',
						'label'         => 'Horizontal block spacing (desktop)',
						'name'          => 'block-spacing-h-desktop',
						'type'          => 'number',
						'instructions'  => 'Change the horizontal spacing for every block on desktop (px)',
						'placeholder'   => '32',
						'default_value' => '32',
						'append'        => 'px',
						'wrapper'       => array(
							'width' => '33',
						),
					),
					array(
						'key'           => 'block_spacing_h_tablet',
						'label'         => 'Horizontal block spacing (tablet)',
						'name'          => 'block-spacing-h-tablet',
						'type'          => 'number',
						'instructions'  => 'Change the horizontal spacing for every block on tablet (px)',
						'placeholder'   => '32',
						'default_value' => '32',
						'append'        => 'px',
						'wrapper'       => array(
							'width' => '33',
						),
					),
					array(
						'key'           => 'block_spacing_h_mobile',
						'label'         => 'Horizontal block spacing (mobile)',
						'name'          => 'block-spacing-h-mobile',
						'type'          => 'number',
						'instructions'  => 'Change the horizontal spacing of every block on mobile (px)',
						'placeholder'   => '32',
						'default_value' => '32',
						'append'        => 'px',
						'wrapper'       => array(
							'width' => '33',
						),
					),
				),
			),
		);

	function webcode_add_colors() {
		$primary_color   = get_field( 'primary-color', 'option' );
		$secondary_color = get_field( 'secondary-color', 'option' );
		$black_color     = get_field( 'black-color', 'option' );
		$white_color     = get_field( 'white-color', 'option' );
		$extra_color_1   = get_field( 'extra-color-1', 'option' );
		$extra_color_2   = get_field( 'extra-color-2', 'option' );
		$extra_color_3   = get_field( 'extra-color-3', 'option' );
		$extra_color_4   = get_field( 'extra-color-4', 'option' );
	};

		//Colors settings (child)
		acf_add_local_field_group(
			array(
				'key'                   => 'colors_setting_fields',
				'title'                 => 'Options',
				'location'              => array(
					array(
						array(
							'param'    => 'options_page',
							'operator' => '==',
							'value'    => 'acf-options-colors',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'seamless',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
				'fields'                => array(
					array(
						'key'           => 'primary_color',
						'label'         => 'Primary color',
						'name'          => 'primary-color',
						'type'          => 'color_picker',
						'instructions'  => 'Choose the primary color for the website',
						'default_value' => '#f47514',
						'return_format' => 'hex',
						'required'      => 1,
						'wrapper'       => array(
							'width' => '25',
						),
					),
					array(
						'key'           => 'secondary_color',
						'label'         => 'Secondary color',
						'name'          => 'secondary-color',
						'type'          => 'color_picker',
						'instructions'  => 'Choose the secondary color for the website',
						'default_value' => '#6254e7',
						'return_format' => 'hex',
						'required'      => 1,
						'wrapper'       => array(
							'width' => '25',
						),
					),
					array(
						'key'           => 'black_color',
						'label'         => 'Black color',
						'name'          => 'black-color',
						'type'          => 'color_picker',
						'instructions'  => 'Choose the black color for the website',
						'default_value' => '#000',
						'return_format' => 'hex',
						'required'      => 1,
						'wrapper'       => array(
							'width' => '25',
						),
					),
					array(
						'key'           => 'white_color',
						'label'         => 'White color',
						'name'          => 'white-color',
						'type'          => 'color_picker',
						'instructions'  => 'Choose the white color for the website',
						'default_value' => '#ffffff',
						'return_format' => 'hex',
						'required'      => 1,
						'wrapper'       => array(
							'width' => '25',
						),
					),
					array(
						'key'           => 'extra_color_1',
						'label'         => 'Extra color',
						'name'          => 'extra-color-1',
						'type'          => 'color_picker',
						'instructions'  => 'Choose an extra color for the website',
						'return_format' => 'hex',
						'required'      => 1,
						'wrapper'       => array(
							'width' => '25',
						),
					),
					array(
						'key'           => 'extra_color_2',
						'label'         => 'Extra color',
						'name'          => 'extra-color-2',
						'type'          => 'color_picker',
						'instructions'  => 'Choose an extra color for the website',
						'return_format' => 'hex',
						'required'      => 1,
						'wrapper'       => array(
							'width' => '25',
						),
					),
					array(
						'key'           => 'extra_color_3',
						'label'         => 'Extra color',
						'name'          => 'extra-color-3',
						'type'          => 'color_picker',
						'instructions'  => 'Choose an extra color for the website',
						'return_format' => 'hex',
						'required'      => 1,
						'wrapper'       => array(
							'width' => '25',
						),
					),
					array(
						'key'           => 'extra_color_4',
						'label'         => 'Extra color',
						'name'          => 'extra-color-4',
						'type'          => 'color_picker',
						'instructions'  => 'Choose an extra color for the website',
						'return_format' => 'hex',
						'required'      => 1,
						'wrapper'       => array(
							'width' => '25',
						),
					),
					array(
						'key'           => 'background_color',
						'label'         => 'Background color',
						'name'          => 'background-color',
						'type'          => 'color_picker',
						'instructions'  => 'Choose the background color for the website',
						'return_format' => 'hex',
						'required'      => 1,
					),
				),
			),
		);

		//Typography settings (child)
		acf_add_local_field_group(
			array(
				'key'                   => 'typography_setting_fields',
				'title'                 => 'Options',
				'location'              => array(
					array(
						array(
							'param'    => 'options_page',
							'operator' => '==',
							'value'    => 'acf-options-typography',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'seamless',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
				'fields'                => array(
					array(
						'key'          => 'google_fonts',
						'label'        => 'Add Google Fonts',
						'name'         => 'google-fonts',
						'type'         => 'repeater',
						'instructions' => 'Add the Google Fonts you want to use in the website',
						'sub_fields'   => array(
							array(
								'key'          => 'google_fonts_link',
								'label'        => 'Font link',
								'name'         => 'link',
								'type'         => 'text',
								'instructions' => 'Past here the link of the font',
								'required'     => 1,
							),
						),
					),
					array(
						'key'          => 'heading_font',
						'label'        => 'Heading font',
						'name'         => 'heading-font',
						'type'         => 'text',
						'instructions' => 'Type the name for all the header fonts (If using Google Fonts, type the name of the font as displayed on fonts.google.com)',
					),
					array(
						'key'          => 'body_font',
						'label'        => 'Body font',
						'name'         => 'body-font',
						'type'         => 'text',
						'instructions' => 'Type the name for the bodytext font (If using Google Fonts, type the name of the font as displayed on fonts.google.com)',
					),
					array(
						'key'        => 'h1_group',
						'label'      => 'H1',
						'name'       => 'h1-group',
						'layout'     => 'table',
						'type'       => 'group',
						'sub_fields' => array(
							array(
								'key'          => 'h1_font_family',
								'label'        => 'Font family',
								'name'         => 'font-family',
								'type'         => 'text',
								'instructions' => 'Leave empty to use selected heading font',
							),
							array(
								'key'           => 'h1_font_size',
								'label'         => 'Font size',
								'name'          => 'font-size',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the font size',
								'default_value' => 70,
							),
							array(
								'key'           => 'h1_line_height',
								'label'         => 'Line height',
								'name'          => 'line-height',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the line height',
								'default_value' => 84,
							),
							array(
								'key'           => 'h1_font_weight',
								'label'         => 'Font weight',
								'name'          => 'font-weight',
								'type'          => 'select',
								'default_value' => '700',
								'instructions'  => 'Choose the font weight',
								'choices'       => array(
									'100' => '100 - Thin',
									'200' => '200 - Extra Light',
									'300' => '300 - Light',
									'400' => '400 - Regular',
									'500' => '500 - Medium',
									'600' => '600 - Semi Bold',
									'700' => '700 - Bold',
									'800' => '800 - Extra Bold',
									'900' => '900 - Black',
								),
							),
							array(
								'key'           => 'h1_font_style',
								'label'         => 'Font style',
								'name'          => 'font-style',
								'type'          => 'select',
								'default_value' => 'normal',
								'instructions'  => 'Choose the font style',
								'choices'       => array(
									'normal'  => 'Normal',
									'italic'  => 'Italic',
									'oblique' => 'Oblique',
								),
							),
							array(
								'key'           => 'h1_margin_bottom',
								'label'         => 'Margin bottom',
								'name'          => 'margin-bottom',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the spacing between the heading and the next element',
								'default_value' => 24,
							),
						),
					),
					array(
						'key'        => 'h2_group',
						'label'      => 'H2',
						'name'       => 'h2-group',
						'layout'     => 'table',
						'type'       => 'group',
						'sub_fields' => array(
							array(
								'key'          => 'h2_font_family',
								'label'        => 'Font family',
								'name'         => 'font-family',
								'type'         => 'text',
								'instructions' => 'Leave empty to use selected heading font',
							),
							array(
								'key'           => 'h2_font_size',
								'label'         => 'Font size',
								'name'          => 'font-size',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the font size',
								'default_value' => 64,
							),
							array(
								'key'           => 'h2_line_height',
								'label'         => 'Line height',
								'name'          => 'line-height',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the line height',
								'default_value' => 70,
							),
							array(
								'key'           => 'h2_font_weight',
								'label'         => 'Font weight',
								'name'          => 'font-weight',
								'type'          => 'select',
								'default_value' => '700',
								'instructions'  => 'Choose the font weight',
								'choices'       => array(
									'100' => '100 - Thin',
									'200' => '200 - Extra Light',
									'300' => '300 - Light',
									'400' => '400 - Regular',
									'500' => '500 - Medium',
									'600' => '600 - Semi Bold',
									'700' => '700 - Bold',
									'800' => '800 - Extra Bold',
									'900' => '900 - Black',
								),
							),
							array(
								'key'           => 'h2_font_style',
								'label'         => 'Font style',
								'name'          => 'font-style',
								'type'          => 'select',
								'default_value' => 'normal',
								'instructions'  => 'Choose the font style',
								'choices'       => array(
									'normal'  => 'Normal',
									'italic'  => 'Italic',
									'oblique' => 'Oblique',
								),
							),
							array(
								'key'           => 'h2_margin_bottom',
								'label'         => 'Margin bottom',
								'name'          => 'margin-bottom',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the spacing between the heading and the next element',
								'default_value' => 24,
							),
						),
					),
					array(
						'key'        => 'h3_group',
						'label'      => 'H3',
						'name'       => 'h3-group',
						'layout'     => 'table',
						'type'       => 'group',
						'sub_fields' => array(
							array(
								'key'          => 'h3_font_family',
								'label'        => 'Font family',
								'name'         => 'font-family',
								'type'         => 'text',
								'instructions' => 'Leave empty to use selected heading font',
							),
							array(
								'key'           => 'h3_font_size',
								'label'         => 'Font size',
								'name'          => 'font-size',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the font size',
								'default_value' => 48,
							),
							array(
								'key'           => 'h3_line_height',
								'label'         => 'Line height',
								'name'          => 'line-height',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the line height',
								'default_value' => 56,
							),
							array(
								'key'           => 'h3_font_weight',
								'label'         => 'Font weight',
								'name'          => 'font-weight',
								'type'          => 'select',
								'default_value' => '700',
								'instructions'  => 'Choose the font weight',
								'choices'       => array(
									'100' => '100 - Thin',
									'200' => '200 - Extra Light',
									'300' => '300 - Light',
									'400' => '400 - Regular',
									'500' => '500 - Medium',
									'600' => '600 - Semi Bold',
									'700' => '700 - Bold',
									'800' => '800 - Extra Bold',
									'900' => '900 - Black',
								),
							),
							array(
								'key'           => 'h3_font_style',
								'label'         => 'Font style',
								'name'          => 'font-style',
								'type'          => 'select',
								'default_value' => 'normal',
								'instructions'  => 'Choose the font style',
								'choices'       => array(
									'normal'  => 'Normal',
									'italic'  => 'Italic',
									'oblique' => 'Oblique',
								),
							),
							array(
								'key'           => 'h3_margin_bottom',
								'label'         => 'Margin bottom',
								'name'          => 'margin-bottom',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the spacing between the heading and the next element',
								'default_value' => 24,
							),
						),
					),
					array(
						'key'        => 'h4_group',
						'label'      => 'H4',
						'name'       => 'h4-group',
						'layout'     => 'table',
						'type'       => 'group',
						'sub_fields' => array(
							array(
								'key'          => 'h4_font_family',
								'label'        => 'Font family',
								'name'         => 'font-family',
								'type'         => 'text',
								'instructions' => 'Leave empty to use selected heading font',
							),
							array(
								'key'           => 'h4_font_size',
								'label'         => 'Font size',
								'name'          => 'font-size',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the font size',
								'default_value' => 36,
							),
							array(
								'key'           => 'h4_line_height',
								'label'         => 'Line height',
								'name'          => 'line-height',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the line height',
								'default_value' => 42,
							),
							array(
								'key'           => 'h4_font_weight',
								'label'         => 'Font weight',
								'name'          => 'font-weight',
								'type'          => 'select',
								'default_value' => '700',
								'instructions'  => 'Choose the font weight',
								'choices'       => array(
									'100' => '100 - Thin',
									'200' => '200 - Extra Light',
									'300' => '300 - Light',
									'400' => '400 - Regular',
									'500' => '500 - Medium',
									'600' => '600 - Semi Bold',
									'700' => '700 - Bold',
									'800' => '800 - Extra Bold',
									'900' => '900 - Black',
								),
							),
							array(
								'key'           => 'h4_font_style',
								'label'         => 'Font style',
								'name'          => 'font-style',
								'type'          => 'select',
								'default_value' => 'normal',
								'instructions'  => 'Choose the font style',
								'choices'       => array(
									'normal'  => 'Normal',
									'italic'  => 'Italic',
									'oblique' => 'Oblique',
								),
							),
							array(
								'key'           => 'h4_margin_bottom',
								'label'         => 'Margin bottom',
								'name'          => 'margin-bottom',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the spacing between the heading and the next element',
								'default_value' => 20,
							),
						),
					),
					array(
						'key'        => 'h5_group',
						'label'      => 'H5',
						'name'       => 'h5-group',
						'layout'     => 'table',
						'type'       => 'group',
						'sub_fields' => array(
							array(
								'key'          => 'h5_font_family',
								'label'        => 'Font family',
								'name'         => 'font-family',
								'type'         => 'text',
								'instructions' => 'Leave empty to use selected heading font',
							),
							array(
								'key'           => 'h5_font_size',
								'label'         => 'Font size',
								'name'          => 'font-size',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the font size',
								'default_value' => 28,
							),
							array(
								'key'           => 'h5_line_height',
								'label'         => 'Line height',
								'name'          => 'line-height',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the line height',
								'default_value' => 36,
							),
							array(
								'key'           => 'h5_font_weight',
								'label'         => 'Font weight',
								'name'          => 'font-weight',
								'type'          => 'select',
								'default_value' => '700',
								'instructions'  => 'Choose the font weight',
								'choices'       => array(
									'100' => '100 - Thin',
									'200' => '200 - Extra Light',
									'300' => '300 - Light',
									'400' => '400 - Regular',
									'500' => '500 - Medium',
									'600' => '600 - Semi Bold',
									'700' => '700 - Bold',
									'800' => '800 - Extra Bold',
									'900' => '900 - Black',
								),
							),
							array(
								'key'           => 'h5_font_style',
								'label'         => 'Font style',
								'name'          => 'font-style',
								'type'          => 'select',
								'default_value' => 'normal',
								'instructions'  => 'Choose the font style',
								'choices'       => array(
									'normal'  => 'Normal',
									'italic'  => 'Italic',
									'oblique' => 'Oblique',
								),
							),
							array(
								'key'           => 'h5_margin_bottom',
								'label'         => 'Margin bottom',
								'name'          => 'margin-bottom',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the spacing between the heading and the next element',
								'default_value' => 20,
							),
						),
					),
					array(
						'key'        => 'h6_group',
						'label'      => 'H6',
						'name'       => 'h6-group',
						'layout'     => 'table',
						'type'       => 'group',
						'sub_fields' => array(
							array(
								'key'          => 'h6_font_family',
								'label'        => 'Font family',
								'name'         => 'font-family',
								'type'         => 'text',
								'instructions' => 'Leave empty to use selected heading font',
							),
							array(
								'key'           => 'h6_font_size',
								'label'         => 'Font size',
								'name'          => 'font-size',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the font size',
								'default_value' => 20,
							),
							array(
								'key'           => 'h6_line_height',
								'label'         => 'Line height',
								'name'          => 'line-height',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the line height',
								'default_value' => 26,
							),
							array(
								'key'           => 'h6_font_weight',
								'label'         => 'Font weight',
								'name'          => 'font-weight',
								'type'          => 'select',
								'default_value' => '700',
								'instructions'  => 'Choose the font weight',
								'choices'       => array(
									'100' => '100 - Thin',
									'200' => '200 - Extra Light',
									'300' => '300 - Light',
									'400' => '400 - Regular',
									'500' => '500 - Medium',
									'600' => '600 - Semi Bold',
									'700' => '700 - Bold',
									'800' => '800 - Extra Bold',
									'900' => '900 - Black',
								),
							),
							array(
								'key'           => 'h6_font_style',
								'label'         => 'Font style',
								'name'          => 'font-style',
								'type'          => 'select',
								'default_value' => 'normal',
								'instructions'  => 'Choose the font style',
								'choices'       => array(
									'normal'  => 'Normal',
									'italic'  => 'Italic',
									'oblique' => 'Oblique',
								),
							),
							array(
								'key'           => 'h6_margin_bottom',
								'label'         => 'Margin bottom',
								'name'          => 'margin-bottom',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the spacing between the heading and the next element',
								'default_value' => 20,
							),
						),
					),
					array(
						'key'        => 'p_group',
						'label'      => 'p',
						'name'       => 'p-group',
						'layout'     => 'table',
						'type'       => 'group',
						'sub_fields' => array(
							array(
								'key'           => 'p_font_size',
								'label'         => 'Font size',
								'name'          => 'font-size',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the font size',
								'default_value' => 16,
							),
							array(
								'key'           => 'p_line_height',
								'label'         => 'Line height',
								'name'          => 'line-height',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the line height',
								'default_value' => 22,
							),
							array(
								'key'           => 'p_font_weight',
								'label'         => 'Font weight',
								'name'          => 'font-weight',
								'type'          => 'select',
								'default_value' => '400',
								'instructions'  => 'Choose the font weight',
								'choices'       => array(
									'100' => '100 - Thin',
									'200' => '200 - Extra Light',
									'300' => '300 - Light',
									'400' => '400 - Regular',
									'500' => '500 - Medium',
									'600' => '600 - Semi Bold',
									'700' => '700 - Bold',
									'800' => '800 - Extra Bold',
									'900' => '900 - Black',
								),
							),
							array(
								'key'           => 'p_font_style',
								'label'         => 'Font style',
								'name'          => 'font-style',
								'type'          => 'select',
								'default_value' => 'normal',
								'instructions'  => 'Choose the font style',
								'choices'       => array(
									'normal'  => 'Normal',
									'italic'  => 'Italic',
									'oblique' => 'Oblique',
								),
							),
							array(
								'key'           => 'p_margin_bottom',
								'label'         => 'Margin bottom',
								'name'          => 'margin-bottom',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the spacing between the heading and the next element',
								'default_value' => 20,
							),
						),
					),
					array(
						'key'        => 'span_group',
						'label'      => 'span',
						'name'       => 'span-group',
						'layout'     => 'table',
						'type'       => 'group',
						'sub_fields' => array(
							array(
								'key'          => 'span_font_family',
								'label'        => 'Font family',
								'name'         => 'font-family',
								'type'         => 'text',
								'instructions' => 'Leave empty to use selected heading font',
							),
							array(
								'key'          => 'span_font_size',
								'label'        => 'Font size',
								'name'         => 'font-size',
								'type'         => 'number',
								'append'       => 'px',
								'instructions' => 'Define the font size (leave empty to set equal to p)',
							),
							array(
								'key'           => 'span_line_height',
								'label'         => 'Line height',
								'name'          => 'line-height',
								'type'          => 'number',
								'append'        => 'px',
								'instructions'  => 'Define the line height (leave empty to set equal to p)',
								'default_value' => 22,
							),
							array(
								'key'           => 'span_font_weight',
								'label'         => 'Font weight',
								'name'          => 'font-weight',
								'type'          => 'select',
								'default_value' => '400',
								'instructions'  => 'Choose the font weight',
								'choices'       => array(
									'100' => '100 - Thin',
									'200' => '200 - Extra Light',
									'300' => '300 - Light',
									'400' => '400 - Regular',
									'500' => '500 - Medium',
									'600' => '600 - Semi Bold',
									'700' => '700 - Bold',
									'800' => '800 - Extra Bold',
									'900' => '900 - Black',
								),
							),
							array(
								'key'           => 'span_font_style',
								'label'         => 'Font style',
								'name'          => 'font-style',
								'type'          => 'select',
								'default_value' => 'normal',
								'instructions'  => 'Choose the font style',
								'choices'       => array(
									'normal'  => 'Normal',
									'italic'  => 'Italic',
									'oblique' => 'Oblique',
								),
							),
							array(
								'key'          => 'span_margin_bottom',
								'label'        => 'Margin bottom',
								'name'         => 'margin-bottom',
								'type'         => 'number',
								'append'       => 'px',
								'instructions' => 'Define the spacing between the heading and the next element (leave empty to set equal to p)',
							),
						),
					),
				),
			),
		);

	//custom post types (child)
	acf_add_local_field_group(
		array(
			'key'                   => 'cpt_setting_fields',
			'title'                 => 'Options',
			'fields'                => array(
				array(
					'key'        => 'new_cpt',
					'label'      => 'Add new Custom Post Type?',
					'name'       => 'add-cpt',
					'type'       => 'repeater',
					'layout'     => 'row',
					'sub_fields' => array(
						array(
							'key'          => 'cpt_name',
							'label'        => 'Name',
							'name'         => 'cpt-name',
							'type'         => 'text',
							'instructions' => 'Type the name of the custom post type',
							'placeholder'  => 'Portfolio',
							'required'     => 1,
						),
						array(
							'key'          => 'cpt_slug',
							'label'        => 'Slug',
							'name'         => 'cpt-slug',
							'type'         => 'text',
							'instructions' => 'Type the slug of the custom post type',
							'placeholder'  => 'portfolio',
							'required'     => 1,
						),
						array(
							'key'          => 'cpt_singular_name',
							'label'        => 'Singular name',
							'name'         => 'cpt-singular-name',
							'type'         => 'text',
							'instructions' => 'Type the singular name of the custom post type',
							'placeholder'  => 'Portfolio item',
							'required'     => 1,
						),
						array(
							'key'          => 'cpt_plural_name',
							'label'        => 'Plural name',
							'name'         => 'cpt-plural-name',
							'type'         => 'text',
							'instructions' => 'Type the plural name of the custom post type',
							'placeholder'  => 'Portfolio items',
							'required'     => 1,
						),
						array(
							'key'          => 'cpt_icon',
							'label'        => 'Icon',
							'name'         => 'cpt-icon',
							'type'         => 'text',
							'instructions' => 'Type the dashicon of the custom post type (https://developer.wordpress.org/resource/dashicons)',
							'placeholder'  => 'dashicons-portfolio',
						),
						array(
							'key'          => 'cpt_supports',
							'label'        => 'Supports',
							'name'         => 'cpt-supports',
							'type'         => 'checkbox',
							'instructions' => 'Choose which features to enable for the custom post type',
							'choices'      => array(
								'editor'    => 'Editor',
								'thumbnail' => 'Thumbnail',
								'excerpt'   => 'Excerpt',
								'single'    => 'Single',
							),
						),
						array(
							'key'               => 'cpt_fields',
							'label'             => 'Fields',
							'name'              => 'cpt-fields',
							'type'              => 'checkbox',
							'instructions'      => 'Select here which fields you want to add to the custom post type',
							'choices'           => array(
								'blocks' => 'Blocks',
							),
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'cpt_supports',
										'operator' => '==',
										'value'    => 'single',
									),
								),
							),
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'acf-options-cpt',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'seamless',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		),
	);

	//taxonomy (child)
	acf_add_local_field_group(
		array(
			'key'                   => 'taxonomy_setting_fields',
			'title'                 => 'Options',
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'acf-options-taxonomy',
					),
				),
			),
			'fields'                => array(
				array(
					'key'        => 'new_tax',
					'label'      => 'Add new taxonomy?',
					'name'       => 'add-tax',
					'type'       => 'repeater',
					'layout'     => 'row',
					'sub_fields' => array(
						array(
							'key'      => 'choose_cpt',
							'label'    => 'Which Custom post type will this taxonomy be attached to?',
							'name'     => 'choose-cpt',
							'type'     => 'text',
							'required' => 1,
						),
						array(
							'key'      => 'tax_name',
							'label'    => 'Name of the taxonomy',
							'name'     => 'tax-name',
							'type'     => 'text',
							'required' => 1,
						),
						array(
							'key'      => 'singular_tax_name',
							'label'    => 'Singular name of the taxonomy',
							'name'     => 'singular-tax-name',
							'type'     => 'text',
							'required' => 1,
						),
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'seamless',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		),
	);

	//header settings (child)
	acf_add_local_field_group(
		array(
			'key'                   => 'header_setting_fields',
			'title'                 => 'Options',
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'acf-options-header',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'seamless',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
			'fields'                => array(
				array(
					'key'     => 'header_layout',
					'label'   => 'Choose a layout for the header',
					'name'    => 'header-layout',
					'type'    => 'radio',
					'layout'  => 'horizontal',
					'choices' => array(
						'layout-1' => 'Layout 1',
						'layout-2' => 'Layout 2',
						'layout-3' => 'Layout 3',
					),
				),
				array(
					'key'           => 'header_padding_v',
					'label'         => 'Header padding vertical',
					'name'          => 'header-padding-v',
					'type'          => 'number',
					'instructions'  => 'Set here the vertical padding for the header',
					'wrapper'       => array(
						'width' => '50',
					),
					'default_value' => 32,
					'append'        => 'px',
				),
				array(
					'key'           => 'header_padding_h',
					'label'         => 'Header padding horizontal',
					'name'          => 'header-padding-h',
					'type'          => 'number',
					'instructions'  => 'Set here the horizontal padding for the header',
					'wrapper'       => array(
						'width' => '50',
					),
					'default_value' => 32,
					'append'        => 'px',
				),
				array(
					'key'           => 'site_logo',
					'label'         => 'Site Logo',
					'name'          => 'site-logo',
					'return_format' => 'id',
					'type'          => 'image',
					'preview_size'  => 'medium',
					'instructions'  => 'Upload here the main logo of the website',
					'wrapper'       => array(
						'width' => '50',
					),
				),
				array(
					'key'               => 'site_logo_sticky',
					'label'             => 'Sticky site Logo',
					'name'              => 'site-logo-sticky',
					'return_format'     => 'id',
					'type'              => 'image',
					'preview_size'      => 'medium',
					'instructions'      => 'Upload here the sticky logo of the website',
					'wrapper'           => array(
						'width' => '50',
					),
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'sticky_header',
								'operator' => '==',
								'value'    => 1,
							),
						),
					),
				),
				array(
					'key'           => 'logo_height',
					'label'         => 'Logo height',
					'instructions'  => 'Define the height of the logo',
					'name'          => 'logo-height',
					'type'          => 'number',
					'default_value' => 72,
					'append'        => 'px',
				),
				array(
					'key'          => 'header_color',
					'label'        => 'Header background color',
					'instructions' => 'Set here the color of the header',
					'name'         => 'header-color',
					'type'         => 'color_picker',
					'wrapper'      => array(
						'width' => '50',
					),
				),
				array(
					'key'           => 'header_color_opacity',
					'label'         => 'Header background color opacity',
					'instructions'  => 'Set here the opacity of the header background',
					'name'          => 'header-color-opacity',
					'type'          => 'range',
					'min'           => 0,
					'max'           => 100,
					'step'          => 1,
					'default_value' => 100,
					'wrapper'       => array(
						'width' => '50',
					),
				),
				array(
					'key'   => 'sticky_header',
					'label' => 'Enable sticky header?',
					'name'  => 'sticky-header',
					'type'  => 'true_false',
				),
				array(
					'key'          => 'menu_font_family',
					'label'        => 'Menu font family',
					'name'         => 'menu-font-family',
					'type'         => 'text',
					'wrapper'      => array(
						'width' => '16',
					),
				),
				array(
					'key'     => 'menu_font_size',
					'label'   => 'Menu font size',
					'name'    => 'menu-font-size',
					'type'    => 'number',
					'append'  => 'px',
					'wrapper' => array(
						'width' => '16',
					),
				),
				array(
					'key'     => 'menu_line_height',
					'label'   => 'Menu line height',
					'name'    => 'menu-line-height',
					'type'    => 'number',
					'append'  => 'px',
					'wrapper' => array(
						'width' => '16',
					),
				),
				array(
					'key'     => 'menu_item_spacing',
					'label'   => 'Menu item spacing',
					'name'    => 'menu-item-spacing',
					'type'    => 'number',
					'append'  => 'px',
					'wrapper' => array(
						'width' => '16',
					),
				),
				array(
					'key'           => 'menu_font_weight',
					'label'         => 'Menu font weight',
					'name'          => 'menu-font-weight',
					'type'          => 'select',
					'default_value' => '400',
					'wrapper'       => array(
						'width' => '16',
					),
					'choices'       => array(
						'100' => '100 - Thin',
						'200' => '200 - Extra Light',
						'300' => '300 - Light',
						'400' => '400 - Regular',
						'500' => '500 - Medium',
						'600' => '600 - Semi Bold',
						'700' => '700 - Bold',
						'800' => '800 - Extra Bold',
						'900' => '900 - Black',
					),
				),
				array(
					'key'           => 'menu_font_style',
					'label'         => 'Font style',
					'name'          => 'menu-font-style',
					'type'          => 'select',
					'default_value' => 'normal',
					'wrapper'       => array(
						'width' => '16',
					),
					'choices'       => array(
						'normal'  => 'Normal',
						'italic'  => 'Italic',
						'oblique' => 'Oblique',
					),
				),
				array(
					'key'          => 'menu_color',
					'label'        => 'Menu text color',
					'instructions' => 'Set here the color of the menu items',
					'name'         => 'menu-color',
					'type'         => 'color_picker',
					'wrapper'      => array(
						'width' => '50',
					),
				),
				array(
					'key'          => 'menu_color_active',
					'label'        => 'Active menu text color',
					'instructions' => 'Set here the color of the active / hovered menu items',
					'name'         => 'menu-color-active',
					'type'         => 'color_picker',
					'wrapper'      => array(
						'width' => '50',
					),
				),
				array(
					'key'               => 'sticky_header_color',
					'label'             => 'Sticky header background color',
					'instructions'      => 'Set here the color of the sticky header',
					'name'              => 'sticky-header-color',
					'type'              => 'color_picker',
					'wrapper'           => array(
						'width' => '50',
					),
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'sticky_header',
								'operator' => '==',
								'value'    => 1,
							),
						),
					),
				),
				array(
					'key'               => 'sticky_header_color_opacity',
					'label'             => 'Sticky header background color opacity',
					'instructions'      => 'Set here the opacity of the sticky header',
					'name'              => 'sticky-header-color-opacity',
					'type'              => 'range',
					'min'               => 0,
					'max'               => 100,
					'step'              => 1,
					'default_value'     => 100,
					'wrapper'           => array(
						'width' => '50',
					),
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'sticky_header',
								'operator' => '==',
								'value'    => 1,
							),
						),
					),
				),
				array(
					'key'               => 'sticky_menu_color',
					'label'             => 'Sticky menu text color',
					'instructions'      => 'Set here the color of the menu items',
					'name'              => 'sticky-menu-color',
					'type'              => 'color_picker',
					'wrapper'           => array(
						'width' => '50',
					),
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'sticky_header',
								'operator' => '==',
								'value'    => 1,
							),
						),
					),
				),
				array(
					'key'               => 'sticky_menu_color_active',
					'label'             => 'Sticky active menu text color',
					'instructions'      => 'Set here the color of the active / hovered menu items',
					'name'              => 'sticky-menu-color-active',
					'type'              => 'color_picker',
					'wrapper'           => array(
						'width' => '50',
					),
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'sticky_header',
								'operator' => '==',
								'value'    => 1,
							),
						),
					),
				),
			),
		),
	);

	add_action( 'init', 'webcode_add_colors', 21 );
	add_action( 'init', 'webcode_get_cpts', 22 );
};
